name: LuLuAICompanion
options:
  bundleIdPrefix: com.lulu-ai
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    MARKETING_VERSION: "1.0.42"
    CURRENT_PROJECT_VERSION: "42"
    SWIFT_VERSION: "5.9"

targets:
  LuLuAICompanion:
    type: application
    platform: macOS
    sources:
      - Sources
      - Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lulu-ai.companion
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/LuLuAICompanion.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/../Frameworks"]
        ENABLE_HARDENED_RUNTIME: YES
    entitlements:
      path: Resources/LuLuAICompanion.entitlements
